### PR TITLE
Apply #8

### LINKED ISSUE #7: Remove closed restaurants
Example: harumonia

### PR DESCRIPTION
**Pull request by mizunashi-mana**
resolve #7 

ref: https://github.com/uecmma/meshi/pull/8#issuecomment-279400647

### CODE REVIEW

**Review by whywaita — APPROVED** [review]
LGTM

**Comment by whywaita** [comment]
plz review @hyr3k / @benevolent0505

**Review by kadokusei — APPROVED** [review]
👍

**Comment by whywaita** [comment]
@benevolent0505 Please check & Review !

**Review by benevolent0505 — COMMENTED** [review]
👍👍👍

**Review by benevolent0505 — APPROVED** [review]

**Comment by whywaita** [comment]
Thank you for review!!

**Comment by whywaita** [comment]
@mizunashi-mana Merged!

**Pull request merged**
